# Cache key for CircleCI. We want to invalidate the cache whenever the Yarn lock file changes.
var_1: &cache_key ngfeatures-{{ checksum "package.json" }}
var_2: &default_docker_image circleci/node:10.12-browsers

# Settings common to each job
var_3: &job_defaults
  working_directory: ~/ngfeatures
  docker:
    - image: *default_docker_image

var_4: &save_cache
  save_cache:
    key: *cache_key
    paths:
    - "node_modules/"

var_5: &npm_install
  run: npm install

jobs:
  lint:
    <<: *job_defaults
    steps:
    - checkout    
    - restore_cache:
        key: *cache_key
    - *npm_install
    - run: npm run lint
    - *save_cache

  unittest:
    <<: *job_defaults
    steps:
    - checkout
    - restore_cache:
        key: *cache_key
    - *npm_install
    - run: npm run test

  e2etest:
    <<: *job_defaults
    steps:
    - checkout
    - run:
        name: Install Chrome
        command: |
          curl -L -o google-chrome.deb https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo dpkg -i google-chrome.deb
          sudo sed -i 's|HERE/chrome\"|HERE/chrome\" --disable-setuid-sandbox|g' /opt/google/chrome/google-chrome
          rm google-chrome.deb
    - restore_cache:
        key: *cache_key
    - *npm_install
    - run: npm run e2e

workflows:
  version: 2
  default_workflow:
    jobs:
    #- lint
    - unittest
    - e2etest